### ISSUE TITLE
Provide example of how to use

### ISSUE THREAD

**Issue by sloganking** [RookAndPawn/text-to-png#2]
I would love to use this, but don't see any documentation how. ``cargo run --release`` outputs

```
USAGE:
    txt2png --color <color> --output <file> --font-size <font-size>
```

Which appears helpful. But I still can't seem to get it to run after attempting to enter those options. 

Can a **Usage** or **Examples** section be added to the readme, that shows a complete list of steps to get this to run?

**Comment by johnhurt** [comment]
Totally. I was working this project over the weekend, but I didn’t check to see if the binary was working. The cli is using clap, so it should give you some usage info if you run it with no args. I’ll check it out this weekend and add the usage to match. Thanks!

**Comment by johnhurt** [comment]
Hey, I just pushed a new version to cargo with some updated features and some changes to the cli output. I just remembered that there is a good usage doc in the cli's folder, so I made that easier to find. For future reference, it's here

https://github.com/RookAndPawn/text-to-png/tree/main/text-to-png-cli

Thanks again for your feedback. I hope you can get some use out of this library :)
